version: 2.1
orbs: 
  heroku: circleci/heroku@1.2.6

jobs: 
  build_test: 
     docker: 
        - image: cimg/node:18.4.0
     environment: 
        HEROKU_API_KEY: 364ff53c-c7d7-4a83-bc8e-1cd10c305243
     steps: 
       - checkout
       - run: 
           name: Run build
           command: npm install --force
       - run: 
            name: Test Javascript project
            command: npm run test
       - store_test_results:
            path: test_results
       - store_artifacts:
            path: test_results
  deploy_app: 
         executor: heroku/default
         steps: 
           - heroku/install
           - heroku/check-authentication
           - heroku/deploy-via-git:
                api-key: HEROKU_API_KEY
                app-name: my-first-ci-deployment
                force: true
                branch: main
      
            
workflows: 
   run_jobs:
      jobs:
      - build_test
      - deploy_app:
          requires: 
             - build_test
