version: 2.1

jobs: 
  build_test_deploy: 
     docker: 
        - image: cimg/node:18.4.0
     steps: 
       - checkout
       - run: 
           name: Run build
           command: npm install
       - run: 
            name: Test Javascript project
            command: npm run test
            
workflows: 
   run_jobs:
      - build_test_deploy
           
